### ISSUE TITLE
Styling comments

### ISSUE THREAD

**Issue by SergeyKanzhelev** [fidmor89/SLAB_AppInsights#2]
1. Do not duplicate `.gitignore` in every folder - one on root level is enough
2. Do not push packages to repo. They will be restored anyway during compilation. Furthermore you have `packages` ignored in `.gitignore`
3. One root-level solution file with all projects will be handy
4. There are some code duplication between the main project and Test solution - context initializers and extensions are duplicated

**Comment by fidmor89** [comment]
Repeated .gitignore have been deleted.
Packages and all files that should be ignored are now being ignored.

number 3 and 4 are a underway.

Thanks for the comments.

**Comment by fidmor89** [comment]
Test solution used to contain some classes from main project (poor testing design) such classes has been removed and the test solution now uses the nuget. so there should be no more code duplicated.
