### ISSUE TITLE
Do not modify TelemetryConfiguraiton.Active in sink constructor

### ISSUE THREAD

**Issue by SergeyKanzhelev** [fidmor89/SLAB_AppInsights#5]
Do not set `TC.Active.InstrumentaitonKey` from the Sink [constructor](https://github.com/fidmor89/SLAB_AppInsights/blob/master/SLAB_AI/SLAB_AI/Sinks/ApplicationInsightsSink.cs#L45). There may be many data collection modules configured for performance counters, dependencies, etc. Every telemetry module should use whatever default instrumentation key customer has set. Typically setting of default configuration will be made in platform-specific manner - reading from environment variable for Azure WebSite, from cscfg for Cloud Service, from ApplicationInsights.config or web.config for on-premesis web application, from app.config for windows form, etc. Data collection modules should respect the default instrumentation key and allow customer to change it in runtime.

**Comment by fidmor89** [comment]
@chepix10 What I get from @SergKanz is that we should not be setting the IK programmatically. instead we should use the one set by the user in the configuration file which is platform specific. and allow the user to change it from code in case they want to use a different one.

**Comment by fidmor89** [comment]
@chepix10 and @chirislash I've made some changes to the code and I believe this issue should be fixed by now. Please help me confirm that. Keep in mind that the test project should be updated to include an iKey the config file.

**Comment by chirislash** [comment]
@fidmor89 @chepix10 We have tested the proyect in both cases, setting the Instrumentation Key programmatically and provided by the customer in this case by the web.config and both work.
