### ISSUE TITLE
NullRef when one of the payload value is null

### ISSUE THREAD

**Issue by mbernard** [fidmor89/SLAB_AppInsights#7]
NullRef when one of the payload value is null

**Comment by mbernard** [comment]
fixed in PR https://github.com/fidmor89/SLAB_AppInsights/pull/8

@fidmor89

**Comment by fidmor89** [comment]
PR merged, Thanks for your contribution

**Comment by mbernard** [comment]
@fidmor89 when do you plan releasing the updated nuget package containing this fix?

**Comment by fidmor89** [comment]
@mbernard sorry for the delay, the publish on nuget.org is underway should be available soon. the updated version is also available in a github release v1.0.4-beta just in case you need it before the nuget.org indexing is finished
https://github.com/fidmor89/SLAB_AppInsights/releases
